#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# init-xinetd-log-perms main
main() {
    # This will prepend service name to all output from here
    exec > >(while read line; do echo "[init-xinetd-log-perms] ${line}"; done) 2>&1

    mkdir -p /config/logs/

    touch /config/logs/xinetd.log
    lsiown -R abc:abc /config/logs/
}
main
